### ISSUE TITLE
README ami image needs to be updated

### ISSUE THREAD

**Issue by cozypet** [schambon/ec2-om#2]
README ami image needs to be updated

**Comment by cozypet** [comment]
SECGROUP=sg-03fc3a1d5906b285e
IMAGE=ami-04b7bf9494d21c5bb
NAMETAG=Han_ops_demo
EXPIREON=2024-12-31
PURPOSETAG=democlient
NUM_HOSTS=3

**Comment by cozypet** [comment]
Above AMI works, tested on 15 Jan

**Comment by schambon** [comment]
Done in a37e667
